#!/bin/bash
#
# Author: Kyrilos Vourlakidis
#
# Email: kvourlakidis@gmail.com
#
# To load this script on shell startup
# add the following line to ~/.bashrc:
# if [-f PATH_TO_THIS_FILE ]; then
# 	source [PATH_TO_THIS_FILE]
# fi
#
# Set the HISTIGNORE property
# Colon-separated list of patterns used
# to decide which command lines should
# be saved on the history list.
# Each pattern is anchored at the beginning
# of the line and must match the complete
# line (no implicit `*' is appended).
HISTIGNORE="&\
:?:??\
:[ \t]*\
:cd:cd \
:clear\
:exit\
:history\
:jobs\
:last\
:ls:ls \
:man\
:mount:umount\
:pwd\
:shutdown\
:top\
:users\
:whoami\
"
#
# Set the PROMPT
#
# Date: \d \D{format}
# Hostname: \h (part) \H (full)
# Jobs: \j
# Newline: \n (lf) \r (cr)
# Time: \t \T \@ \A
# User: \u
# CWD: \w (full) \W (basename)
# Command number: \! \#
#
# Default prompt (without color information):
# \u@\h:\w$
# 
COLR="\[\033[01;31m\]"
COLG="\[\033[01;32m\]"
COLY="\[\033[01;33m\]"
COLB="\[\033[01;34m\]"
CEND="\[\033[00m\]"
#
PS1="\n$COLY\j$CEND|$COLB\A$CEND|$COLB\D{%d-%m-%y}$CEND|$COLY\u@\h$CEND|$COLR\$?$CEND\n$COLG\w$CEND\n\$ "
#
# Aliases
alias cdp="cd $HOME/Projects"
alias cdd="cd $HOME/Projects/dev-utils"
alias rm="rm -iv"

