#!/bin/bash
#
# Author: Kyrilos Vourlakidis
#
# Email: kvourlakidis@gmail.com
#
# To load this script on shell startup
# add the following line to ~/.bashrc:
# if [-f PATH_TO_THIS_FILE ]; then
# 	source [PATH_TO_THIS_FILE]
# fi
#
# Set the HISTIGNORE property
# Colon-separated list of patterns used
# to decide which command lines should
# be saved on the history list.
# Each pattern is anchored at the beginning
# of the line and must match the complete
# line (no implicit `*' is appended).
HISTIGNORE="&\
:?:??\
:[ \t]*\
:cd *\
:clear\
:exit\
:history\
:jobs\
:last\
:ls *\
:man:man *\
:mount:umount\
:pwd\
:shutdown\
:top\
:users\
:whoami\
"
#
# Set the PROMPT
# 
# Default prompt:
# \u@\h:\w$
# Default prompt with color (split up for readability):
# \[\033[01;32m\]\u@\h
# \[\033[00m\]:
# \[\033[01;34m\]\w
# \[\033[00m\]\$
# 
COLR="\[\033[01;31m\]"
COLG="\[\033[01;32m\]"
COLB="\[\033[01;34m\]"
CEND="\[\033[00m\]"
export PS1="$COLB\!$CEND|$COLR\$?$CEND|$COLG\u$CEND:$COLB\W$CEND\$ "

